-- 코드를 입력하세요
SELECT C.ANIMAL_ID, C.NAME
FROM (
SELECT A.ANIMAL_ID, A.NAME, ROW_NUMBER() OVER (ORDER BY TIMESTAMPDIFF(SECOND, B.DATETIME, A.DATETIME)) AS 'RANK'
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY 'RANK'
LIMIT 2
) C