-- 코드를 입력하세요
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN (
    SELECT REST_ID, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS 'RANK'
    FROM REST_INFO
) B
ON A.REST_ID = B.REST_ID
WHERE B.RANK = 1
ORDER BY A.FOOD_TYPE DESC
