SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT OS.USER_ID) / UI.TOTAL_COUNT, 1) AS PURCHASED_RATIO
FROM 
(
    SELECT USER_ID, YEAR(JOINED) AS YEAR, MONTH(JOINED) AS MONTH, COUNT(*) OVER (PARTITION BY YEAR(JOINED)) AS TOTAL_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR, MONTH