SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * FO.AMOUNT AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) FO
LEFT JOIN FOOD_PRODUCT FP
ON FO.PRODUCT_ID = FP.PRODUCT_ID
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
