SELECT HE.EMP_NO, HE.EMP_NAME, HG.GRADE,
    CASE
    WHEN GRADE = 'S' THEN HE.SAL * 0.2
    WHEN GRADE = 'A' THEN HE.SAL * 0.15
    WHEN GRADE = 'B' THEN HE.SAL * 0.1
    ELSE 0
    END AS BONUS
FROM 
    (SELECT EMP_NO,
        CASE
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
        END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO) HG
JOIN HR_EMPLOYEES HE
ON HG.EMP_NO = HE.EMP_NO
ORDER BY EMP_NO