SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
LEFT JOIN MEMBER_PROFILE MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN 
(SELECT MAX_MEMBER.MEMBER_ID FROM (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
) MAX_MEMBER)
ORDER BY REVIEW_DATE, REVIEW_TEXT