-- 코드를 작성해주세요
SELECT O.ITEM_ID, O.ITEM_NAME, O.RARITY
FROM ITEM_INFO O
JOIN ITEM_TREE T
ON O.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY='RARE'
)
ORDER BY O.ITEM_ID DESC;